-- Load demo data from CSVs (last week of Feb 2026)
-- Upload CSVs in snowflake/data to a stage, then run COPY INTO.

USE DATABASE TELCO_AI_DB;
USE SCHEMA NETWORK_ASSURANCE;
USE WAREHOUSE TELCO_ASSURANCE_WH;

-- 1) File format and stage
CREATE OR REPLACE FILE FORMAT TELCO_CSV_FF
  TYPE = CSV
  FIELD_DELIMITER = ','
  SKIP_HEADER = 1
  TRIM_SPACE = TRUE
  FIELD_OPTIONALLY_ENCLOSED_BY = '\"'
  NULL_IF = ('', 'NULL');

CREATE OR REPLACE STAGE TELCO_DATA_STAGE
  FILE_FORMAT = TELCO_CSV_FF;

-- 2) Upload CSVs to stage
-- Snowsight: use Data > Stages > TELCO_DATA_STAGE > Load Files
-- SnowSQL example:
--   PUT file:///path/to/repo/snowflake/data/network_kpi.csv @TELCO_DATA_STAGE AUTO_COMPRESS=TRUE;
--   PUT file:///path/to/repo/snowflake/data/alarms.csv @TELCO_DATA_STAGE AUTO_COMPRESS=TRUE;
--   PUT file:///path/to/repo/snowflake/data/topology.csv @TELCO_DATA_STAGE AUTO_COMPRESS=TRUE;
--   PUT file:///path/to/repo/snowflake/data/incidents.csv @TELCO_DATA_STAGE AUTO_COMPRESS=TRUE;

-- 3) Load data
TRUNCATE TABLE NETWORK_KPI;
TRUNCATE TABLE ALARMS;
TRUNCATE TABLE TOPOLOGY;
TRUNCATE TABLE INCIDENTS;
TRUNCATE TABLE SITE_GEO;
TRUNCATE TABLE SERVICE_FOOTPRINTS;
TRUNCATE TABLE CHANGE_EVENTS;
TRUNCATE TABLE TROUBLE_TICKETS;
TRUNCATE TABLE SLA_BREACHES;
TRUNCATE TABLE ANOMALY_SCORES;
TRUNCATE TABLE CMDB_CI;
TRUNCATE TABLE CMDB_RELATIONSHIPS;
TRUNCATE TABLE EVENT_CORRELATION_RULES;

COPY INTO NETWORK_KPI
  FROM @TELCO_DATA_STAGE/network_kpi_part1.csv
  FILE_FORMAT = (FORMAT_NAME = TELCO_CSV_FF)
  ON_ERROR = 'ABORT_STATEMENT';

COPY INTO NETWORK_KPI
  FROM @TELCO_DATA_STAGE/network_kpi_part2.csv
  FILE_FORMAT = (FORMAT_NAME = TELCO_CSV_FF)
  ON_ERROR = 'ABORT_STATEMENT';

COPY INTO ALARMS
  FROM @TELCO_DATA_STAGE/alarms.csv
  FILE_FORMAT = (FORMAT_NAME = TELCO_CSV_FF)
  ON_ERROR = 'ABORT_STATEMENT';

COPY INTO TOPOLOGY
  FROM @TELCO_DATA_STAGE/topology.csv
  FILE_FORMAT = (FORMAT_NAME = TELCO_CSV_FF)
  ON_ERROR = 'ABORT_STATEMENT';

COPY INTO INCIDENTS
  FROM @TELCO_DATA_STAGE/incidents.csv
  FILE_FORMAT = (FORMAT_NAME = TELCO_CSV_FF)
  ON_ERROR = 'ABORT_STATEMENT';

COPY INTO SITE_GEO
  FROM @TELCO_DATA_STAGE/site_geo.csv
  FILE_FORMAT = (FORMAT_NAME = TELCO_CSV_FF)
  ON_ERROR = 'ABORT_STATEMENT';

COPY INTO SERVICE_FOOTPRINTS
  FROM @TELCO_DATA_STAGE/service_footprints.csv
  FILE_FORMAT = (FORMAT_NAME = TELCO_CSV_FF)
  ON_ERROR = 'ABORT_STATEMENT';

COPY INTO CHANGE_EVENTS
  FROM @TELCO_DATA_STAGE/change_events.csv
  FILE_FORMAT = (FORMAT_NAME = TELCO_CSV_FF)
  ON_ERROR = 'ABORT_STATEMENT';

COPY INTO TROUBLE_TICKETS
  FROM @TELCO_DATA_STAGE/trouble_tickets.csv
  FILE_FORMAT = (FORMAT_NAME = TELCO_CSV_FF)
  ON_ERROR = 'ABORT_STATEMENT';

COPY INTO SLA_BREACHES
  FROM @TELCO_DATA_STAGE/sla_breaches.csv
  FILE_FORMAT = (FORMAT_NAME = TELCO_CSV_FF)
  ON_ERROR = 'ABORT_STATEMENT';

COPY INTO ANOMALY_SCORES
  FROM @TELCO_DATA_STAGE/anomaly_scores.csv
  FILE_FORMAT = (FORMAT_NAME = TELCO_CSV_FF)
  ON_ERROR = 'ABORT_STATEMENT';

COPY INTO CMDB_CI
  FROM @TELCO_DATA_STAGE/cmdb_ci.csv
  FILE_FORMAT = (FORMAT_NAME = TELCO_CSV_FF)
  ON_ERROR = 'ABORT_STATEMENT';

COPY INTO CMDB_RELATIONSHIPS
  FROM @TELCO_DATA_STAGE/cmdb_relationships.csv
  FILE_FORMAT = (FORMAT_NAME = TELCO_CSV_FF)
  ON_ERROR = 'ABORT_STATEMENT';

COPY INTO EVENT_CORRELATION_RULES
  FROM @TELCO_DATA_STAGE/event_correlation_rules.csv
  FILE_FORMAT = (FORMAT_NAME = TELCO_CSV_FF)
  ON_ERROR = 'ABORT_STATEMENT';
