-- Snowflake provisioning for Telecom Assurance demo
-- Creates roles, user, warehouse, database, schema, and MCP server.
-- Run with ACCOUNTADMIN or equivalent privileges.

-- 1) Roles
CREATE ROLE IF NOT EXISTS TELCO_ADMIN_RL;
CREATE ROLE IF NOT EXISTS TELCO_MCP_RL;
CREATE ROLE IF NOT EXISTS TELCO_SN_INTEGRATION_RL;

-- 2) Warehouse
CREATE WAREHOUSE IF NOT EXISTS TELCO_ASSURANCE_WH
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE;

GRANT USAGE, OPERATE ON WAREHOUSE TELCO_ASSURANCE_WH TO ROLE TELCO_ADMIN_RL;
GRANT USAGE ON WAREHOUSE TELCO_ASSURANCE_WH TO ROLE TELCO_MCP_RL;
GRANT USAGE ON WAREHOUSE TELCO_ASSURANCE_WH TO ROLE TELCO_SN_INTEGRATION_RL;

-- 3) Database + schema
CREATE DATABASE IF NOT EXISTS TELCO_AI_DB;
CREATE SCHEMA IF NOT EXISTS TELCO_AI_DB.NETWORK_ASSURANCE;

GRANT USAGE ON DATABASE TELCO_AI_DB TO ROLE TELCO_ADMIN_RL;
GRANT USAGE ON SCHEMA TELCO_AI_DB.NETWORK_ASSURANCE TO ROLE TELCO_ADMIN_RL;
GRANT USAGE ON DATABASE TELCO_AI_DB TO ROLE TELCO_MCP_RL;
GRANT USAGE ON SCHEMA TELCO_AI_DB.NETWORK_ASSURANCE TO ROLE TELCO_MCP_RL;
GRANT USAGE ON DATABASE TELCO_AI_DB TO ROLE TELCO_SN_INTEGRATION_RL;
GRANT USAGE ON SCHEMA TELCO_AI_DB.NETWORK_ASSURANCE TO ROLE TELCO_SN_INTEGRATION_RL;

-- 4) User (set a strong temporary password and rotate after first login)
CREATE USER IF NOT EXISTS TELCO_MCP_USER
  PASSWORD = '<TEMP_PASSWORD>'
  LOGIN_NAME = 'TELCO_MCP_USER'
  DISPLAY_NAME = 'TELCO MCP User'
  DEFAULT_ROLE = TELCO_MCP_RL
  DEFAULT_WAREHOUSE = TELCO_ASSURANCE_WH
  MUST_CHANGE_PASSWORD = TRUE;

GRANT ROLE TELCO_MCP_RL TO USER TELCO_MCP_USER;
-- Create a separate admin user if needed; keep integration users least-privilege.

-- 5) MCP server (managed by Snowflake)
USE DATABASE TELCO_AI_DB;
USE SCHEMA NETWORK_ASSURANCE;

CREATE OR REPLACE MCP SERVER TELCO_ASSURANCE_MCP
FROM SPECIFICATION $$
  tools:
    - title: "SQL Execution Tool"
      name: "sql_exec_tool"
      type: "SYSTEM_EXECUTE_SQL"
      description: "Execute SQL queries on telecom assurance views."
$$;

GRANT USAGE ON MCP SERVER TELCO_AI_DB.NETWORK_ASSURANCE.TELCO_ASSURANCE_MCP
  TO ROLE TELCO_MCP_RL;
GRANT USAGE ON MCP SERVER TELCO_AI_DB.NETWORK_ASSURANCE.TELCO_ASSURANCE_MCP
  TO ROLE TELCO_SN_INTEGRATION_RL;

-- 6) Data access grants (apply after demo_setup.sql creates tables/views)
GRANT SELECT ON ALL TABLES IN SCHEMA TELCO_AI_DB.NETWORK_ASSURANCE TO ROLE TELCO_MCP_RL;
GRANT SELECT ON ALL VIEWS IN SCHEMA TELCO_AI_DB.NETWORK_ASSURANCE TO ROLE TELCO_MCP_RL;
GRANT SELECT ON ALL TABLES IN SCHEMA TELCO_AI_DB.NETWORK_ASSURANCE TO ROLE TELCO_SN_INTEGRATION_RL;
GRANT SELECT ON ALL VIEWS IN SCHEMA TELCO_AI_DB.NETWORK_ASSURANCE TO ROLE TELCO_SN_INTEGRATION_RL;

-- Ensure future tables/views are also granted
ALTER SCHEMA TELCO_AI_DB.NETWORK_ASSURANCE
  SET DEFAULT_DDL_GRANTS = 'SELECT ON TABLES TO ROLE TELCO_MCP_RL, SELECT ON VIEWS TO ROLE TELCO_MCP_RL, SELECT ON TABLES TO ROLE TELCO_SN_INTEGRATION_RL, SELECT ON VIEWS TO ROLE TELCO_SN_INTEGRATION_RL';

-- 7) Optional: OAuth integration for MCP clients
/*
CREATE OR REPLACE SECURITY INTEGRATION TELCO_MCP_OAUTH
  TYPE = OAUTH
  OAUTH_CLIENT = CUSTOM
  ENABLED = TRUE
  OAUTH_CLIENT_TYPE = 'CONFIDENTIAL'
  OAUTH_REDIRECT_URI = '<redirect_uri>';

SELECT SYSTEM$SHOW_OAUTH_CLIENT_SECRETS('TELCO_MCP_OAUTH');
*/
